[package]
name = "transaction_parser"
version = "0.1.0"
authors = ["James Mayclin <29185101+jmayclin@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"